# https://kind.sigs.k8s.io/docs/user/quick-start/#advanced
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker