apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-1
  labels:
    dept: dept-1
    team: team-a
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8081
      env:
        - name: PORT
          value: "8081"
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-2
  labels:
    dept: dept-2
    team: team-b
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8082
      env:
        - name: PORT
          value: "8082"
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-3
  labels:
    dept: dept-3
    team: team-c
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8083
          name: "exposed-port"
      env:
        - name: PORT
          value: "8083"
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    purpose: practice
spec:
  restartPolicy: Always
  containers:
    - name: ubuntu-container
      imagePullPolicy: IfNotPresent
      image: ubuntu/redis
      ports:
        - containerPort: 6379
          name: "redis-port"
          hostIP: localhost
          hostPort: 6379
          protocol: TCP
      env:
        - name: REDIS_PASSWORD
          value: secret
