services:
  postgres:
    image: 'postgres:latest'
    container_name: 'gateway_compose_container'
    restart: no
    environment:
      - 'POSTGRES_DB=microservice_1'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '7081:5432'

  zipkin-server:
    image: 'openzipkin/zipkin:latest'
    container_name: 'zipkin_compose_container'
    restart: no
    ports:
      - '9411:9411'

