services:
  postgres:
    image: 'postgres:latest'
    container_name: 'redisson_container'
    restart: no
    environment:
      - 'POSTGRES_DB=redisson_db'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5481:5432'
    volumes:
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#      - ./src/test/resources/db/postgres/data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    container_name: redisson_dc
    restart: no
    ports:
      - "16379:6379"
    volumes:
      - ./src/test/resources/db/redis:/bitnami/redis/data
    environment:
      - REDIS_DATABASE=redis
      - REDIS_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data: