services:
  postgres:
    image: 'postgres:latest'
    container_name: 'webflux_postgres'
    restart: unless-stopped
    env_file:
      - ./.env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5581:5432'
    volumes:
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
