services:
  postgres:
    image: 'postgres:latest'
    container_name: 'reactive_compose_container'
    restart: no
    environment:
      - 'POSTGRES_DB=reactive_db'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '4002:5432'
