services:
  postgres:
    image: 'postgres:latest'
    container_name: 'config_server_compose_container'
    restart: no
    environment:
      - 'POSTGRES_DB=microservice_1'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '7073:5432'
    volumes:
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  rabbit-mq:
    image: 'rabbitmq:3-management'
    container_name: 'gateway_broker_container'
    restart: no
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - full_stack_v5_network

networks:
  full_stack_v5_network:
    driver: bridge
    name: full_stack_v5_network
