create schema if not exists sys_org;
alter schema sys_org owner to admin;

set search_path = 'sys_org';

drop table if exists sys_org.student;
drop table if exists sys_org.hotel;
drop table if exists sys_org.guide;

drop sequence if exists sys_org.guide_id_seq;
drop sequence if exists sys_org.student_id_seq;
drop sequence if exists sys_org.hotel_id_seq;

create sequence if not exists sys_org.guide_id_seq;
create sequence if not exists sys_org.student_id_seq;
create sequence if not exists sys_org.hotel_id_seq;

create table if not exists sys_org.guide
(
    id                      bigint generated by default as identity
        primary key,
    created_by_user         varchar(255)             not null,
    created_timestamp       timestamp with time zone not null,
    last_modified_by_user   varchar(255),
    last_modified_timestamp timestamp with time zone,
    name                    varchar(255)             not null,
    salary                  numeric(38, 2),
    staff_id                varchar(255)
        constraint unique_staff_id_constraint
            unique
);

alter table sys_org.guide
    owner to admin;

create table sys_org.hotel
(
    id                      bigint generated by default as identity
        primary key,
    created_by_user         varchar(255)             not null,
    created_timestamp       timestamp with time zone not null,
    last_modified_by_user   varchar(255),
    last_modified_timestamp timestamp with time zone,
    name                    varchar(255)
);

alter table sys_org.hotel
    owner to admin;

create table if not exists sys_org.student
(
    id                      bigint generated by default as identity
        primary key,
    created_by_user         varchar(255)             not null,
    created_timestamp       timestamp with time zone not null,
    last_modified_by_user   varchar(255),
    last_modified_timestamp timestamp with time zone,
    enrollment_id           varchar(255)             not null
        constraint unique_enrollment_id_constraint
            unique,
    name                    varchar(255)             not null,
    guide_id                bigint
        constraint fk_on_guide_id_constraint
            references sys_org.guide,
    hotel_id bigint
        constraint fk_on_hotel_constraint
            references sys_org.hotel
);



alter table sys_org.student
    owner to admin;

INSERT INTO sys_org.guide (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp, name,
                           salary, staff_id)
VALUES (176, 'AJ', '2025-01-09 21:20:06.012557 +00:00', null, null, 'Aadinath Singh', 35575.04, 'ABE89272');

INSERT INTO sys_org.guide (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp, name,
                           salary, staff_id)
VALUES (177, 'AJ', '2025-01-09 21:20:06.216823 +00:00', null, null, 'Anand Bhattacharya', 26989.01, 'AZR01178');



INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (683, 'AJ', '2025-01-09 21:20:06.133231 +00:00', null, null, 'zUA85203', 'Navin Nayar', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (684, 'AJ', '2025-01-09 21:20:06.140052 +00:00', null, null, 'zJW26354', 'Narayan Butt', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (685, 'AJ', '2025-01-09 21:20:06.143864 +00:00', null, null, 'zZU93515', 'Ms. Vidhya Singh', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (686, 'AJ', '2025-01-09 21:20:06.148286 +00:00', null, null, 'zPT76662', 'Anuja Embranthiri', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (687, 'AJ', '2025-01-09 21:20:06.153640 +00:00', null, null, 'zTA79814', 'Rageshwari Panicker V', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (688, 'AJ', '2025-01-09 21:20:06.159911 +00:00', null, null, 'zKS37311', 'Javas Somayaji DDS', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (689, 'AJ', '2025-01-09 21:20:06.166537 +00:00', null, null, 'zUP61528', 'Sukanya Nehru', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (690, 'AJ', '2025-01-09 21:20:06.171468 +00:00', null, null, 'zTR01512', 'Anjushree Bhattathiri', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (691, 'AJ', '2025-01-09 21:20:06.178662 +00:00', null, null, 'zDA13148', 'Gorakhanatha Khatri', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (692, 'AJ', '2025-01-09 21:20:06.184872 +00:00', null, null, 'zRH28250', 'Elakshi Reddy II', 176);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (693, 'AJ', '2025-01-09 21:20:06.222923 +00:00', null, null, 'zXQ17787', 'Dr. Keerti Kaul', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (694, 'AJ', '2025-01-09 21:20:06.228185 +00:00', null, null, 'zMP08349', 'Mandaakin Rana', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (695, 'AJ', '2025-01-09 21:20:06.233450 +00:00', null, null, 'zPP44795', 'Sukanya Bhattathiri', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (696, 'AJ', '2025-01-09 21:20:06.239188 +00:00', null, null, 'zLE15600', 'Swapnil Butt', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (697, 'AJ', '2025-01-09 21:20:06.245569 +00:00', null, null, 'zQB08958', 'Dwaipayana Ganaka', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (698, 'AJ', '2025-01-09 21:20:06.249967 +00:00', null, null, 'zGK69932', 'Bala Mukhopadhyay', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (699, 'AJ', '2025-01-09 21:20:06.254313 +00:00', null, null, 'zJO11216', 'Ekaling Khan', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (700, 'AJ', '2025-01-09 21:20:06.258381 +00:00', null, null, 'zUR35315', 'Alok Bhat', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (701, 'AJ', '2025-01-09 21:20:06.263910 +00:00', null, null, 'zMY29593', 'Uma Namboothiri', 177);

INSERT INTO sys_org.student (id, created_by_user, created_timestamp, last_modified_by_user, last_modified_timestamp,
                             enrollment_id, name, guide_id)
VALUES (702, 'AJ', '2025-01-09 21:20:06.267760 +00:00', null, null, 'zCV12890', 'Dr. Deepan Mishra', 177);


