services:
  postgres:
    image: 'postgres:latest'
    container_name: "sdj_hibernate_container"
    environment:
      - 'POSTGRES_DB=spring-data-jpa-hibernate'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5434:5432'
    volumes:
      - ./src/test/resources/data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
