services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=spring-data-jpa-hibernate'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5434:5432'
