services:
  postgres:
    image: 'postgres:latest'
    container_name: 'auth_db_container'
    restart: no
    environment:
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5488:5432'
    volumes:
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro