services:
  postgres:
    image: 'postgres:latest'
    container_name: 'discovery_server_compose_container'
    restart: no
    environment:
      - 'POSTGRES_DB=microservice_1'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '7001:5432'
    volumes:
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro