apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 8081
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: ubuntu
      image: ubuntu
      ports:
        - containerPort: 80
      args:
        - "/bin/sh"
        - "-c"
        - "echo Ubuntu running...; sleep infinity"