apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      env:
        - name: PORT
          value: "8080"
#      args:
#        - "/bin/sh"
#        - "-c"
#        - "echo nginx started...; printenv"

