apiVersion: v1
kind: Pod
metadata:
  name: custom-nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      startupProbe:
        httpGet:
          port: 80
          path: /
          scheme: HTTP
        periodSeconds: 1
        failureThreshold: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: custom-mongo
spec:
  containers:
    - name: mongo-container
      image: mongo
      startupProbe:
        tcpSocket:
          port: 27017
        periodSeconds: 1
        failureThreshold: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: custom-ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      args:
        - "/bin/sh"
        - "-c"
        - "echo Ubuntu Started; printenv; sleep infinity"
