apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
#  Remember you are selecting the 'pod' here, not the deployment
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80